services:
  - type: web
    name: aod-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: COOKIE_PATH
        value: canvas_cookies.json